use_frameworks!

platform :ios, '9.0'

target 'TextfieldPodLibEn_Example' do
  pod 'TextfieldPodLibEn', :path => '../'

  target 'TextfieldPodLibEn_Tests' do
    inherit! :search_paths

    
  end
end
